from .utils.pypose_compile import maybe_install_pypose_torch_compile_monkeypatch
from .utils.pypose_ambient_grad import maybe_install_pypose_ambient_grad_monkeypatch

maybe_install_pypose_torch_compile_monkeypatch()
maybe_install_pypose_ambient_grad_monkeypatch()
